spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: ${MICROSERVICE_USER_URI:http://localhost:8090}
          predicates:
            - Path=/api/user/**
        - id: book
          uri: ${MICROSERVICE_BOOK_URI:http://localhost:8091}
          predicates:
            - Path=/api/book/**
        - id: booking
          uri: ${MICROSERVICE_BOOKING_URI:http://localhost:8092}
          predicates:
            - Path=/api/booking/**

server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka/}