spring:
  data:
    mongodb:
      uri: mongodb+srv://libraryUSER:app@cluster0.z8k6amp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: libraryDB
server:
  port: 8092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8070/eureka/}

microservices:
  user: ${MICROSERVICE_USER_URI:http://localhost:8090}
  book: ${MICROSERVICE_BOOK_URI:http://localhost:8091}
