spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/pablotsky321/libraryapp
          search-paths: config-data
server:
  port: 8888
